duckdb_local:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('VD_EPHM_DUCKDB_PATH') }}"
      schema: main
    prod:
      type: duckdb
      path: "{{ env_var('VD_DOMAIN_DUCKDB_PATH') }}"
      schema: main
